CONFIG_ZMK_POINTING=y
CONFIG_ZMK_IDLE_TIMEOUT=300000
CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y
CONFIG_ZMK_AMBIENT_LIGHT=y
CONFIG_ZMK_AMBIENT_LIGHT_POLL_INTERVAL_MS=500
CONFIG_DONGLE_SCREEN_AMBIENT_LIGHT=y
