name: "Build Adam's Totem"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_left rgbled_adapter", "totem_right rgbled_adapter", "totem_dongle dongle_screen", "settings_reset"]'
      alphas: '["colemak"]'
      clipboard: '["mac"]'
      extra: '["qwerty"]'
      tap: '["colemak"]'
      branches: '["eg0n/zmk/totem"]'
      modules: '["eg0n/zmk-totem-dongle/main caksoylar/zmk-rgbled-widget/v0.3.0 eg0n/zmk-dongle-screen/lightsensor"]'
      dts_extra_cppflags: '["MIRYOKU_KLUDGE_GLOBALSHIFTFUNCTIONS RGBLED_WIDGET_BEHAVIORS DONGLE_SCREEN_BRIGHTNESS_BEHAVIORS"]'
